-- 回滚：000001_init
DROP SCHEMA IF EXISTS promotion   CASCADE;
DROP SCHEMA IF EXISTS fulfillment CASCADE;
DROP SCHEMA IF EXISTS payments    CASCADE;
DROP SCHEMA IF EXISTS orders      CASCADE;
DROP SCHEMA IF EXISTS users       CASCADE;
DROP SCHEMA IF EXISTS inventory   CASCADE;
DROP SCHEMA IF EXISTS catalog     CASCADE;
DROP SCHEMA IF EXISTS admin       CASCADE;
DROP FUNCTION IF EXISTS set_updated_at() CASCADE;
